[[redirects]]
  from = "/api/*"
  to = "https://api.ffzyapi.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/video-proxy/*"
  to = ":splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"